query ListUsuario($dto: GenericListInput!) {
  list: listUsuario(dto: $dto) {
    total

    offset

    limit

    items {
      id

      nome
      email
      matriculaSiape

      cargos {
        id
        slug
      }

      dateCreated
      dateUpdated
      dateDeleted
      dateSearchSync
    }
  }
}
