query UsuarioFindById($id: Int!) {
  usuario: findUsuarioById(dto: { id: $id }) {
    id

    nome
    email
    matriculaSiape

    dateCreated
    dateUpdated
    dateDeleted

    cargos {
      id
      slug
    }
  }
}
